.github/workflows/nox.yml
For some reason running the tests with Python 3.12 takes very long. For now, simply disable testing with 3.12.
=> chore: Disable test on Python 3.12

cluster_utils/job_manager.py
WatchedFileHandler checks if the file changed or is unavailable for writing before logging, and if so, reopens it. This is helpful when the log file gets closed due to intermittent problems with the file system.
How I tested?
Running the local example, checking if logs are still written to the file.
Closes #86.
=> Change logging to use WatchedFileHandler

.pre-commit-config.yaml
This config setting made the pre-commit environment dependent on having that Python version installed, rendering pre-commit unusable for other Python versions.
=> Remove language version from black in pre-commit

cluster_utils/job.py, cluster_utils/slurm_cluster_system.py, docs/configuration.rst, docs/examples/index.rst, docs/examples/slurm_timeout_signal.rst, docs/index.rst, examples/slurm_timeout_signal/grid_search.toml, examples/slurm_timeout_signal/main.py, tests/test_slurm_cluster_system.py
Add option to send signal to jobs before they are killed by timeout.
Add a new option `timeout_signal_time` in the cluster_requirements section.  If set, it adds `--signal=USR1@<time>` to the `sbatch` call, resulting in Slurm to send a USR1 signal at the specified time (in seconds) before it would kill the job due to timeout.
For the signal to actually be sent to the process running the main script, this needs to be executed with `srun`, so some change in the job command creation is needed to inject that for Slurm jobs.
Also add an example and embed it in the documentation.
Resolves #64.
By running the example.
=> Slurm: Add new option to send USR1 signal before timeout

docs/report.rst
This is useful for cluster systems which don't have all necessary packages installed to generate the report.
Closes #72.
=> doc: Show how to use container for pdflatex

cluster_utils/settings.py, docs/conf.py, docs/examples/checkpointing.rst, docs/examples/index.rst, docs/examples/slurm_timeout_signal.rst, docs/exit_for_resume.rst, docs/index.rst, examples/checkpointing/checkpoint_example.py
This is a rather important feature of cluster_utils but it seems it wasn't explained anywhere so far.
The screenshot below shows how the rendered page looks.
=> doc: Add basic how-to page for exit_for_resume()

docs/conf.py, docs/configuration.rst, pyproject.toml
This makes the rendering of the configuration page a bit nicer and, more importantly, allows to link/reference individual parameters.
Parameters can be added with
```rst
.. confval: namespace.foo: type = default_value
[description]
```
and can be referenced in other parts of the documentation with
```rst
:confval:`namespace.foo`
```
Can probably still be improved a bit (e.g. I'd like to have a better way to mark required parameters) but I think it's already quite an improvement to before.
Example on how it looks like:
=> doc: Use custom object type 'confval' for configuration

cluster_utils/slurm_cluster_system.py, tests/test_slurm_cluster_system.py
_Re-creation of #96 (apparently I can't re-open the old one after a force push...)_
Move the parsing of the output of sacct to a separate function, so it can be unit-tested.
I also found out that by adding `-X` I can limit the output to only the cumulative statistics of each job, omitting the intermediate results (*.batch, etc.) which were skipped in the parsing anyway.
Note: I started this as I initially thought parsing of the sacct output would need to get more complex in order to address https://github.com/martius-lab/cluster_utils/issues/87, so I wanted to be able to add unit tests. It turned out that there is a better, much easier fix for that issue but I think testability of the parsing is good to have anyway, so I'm still submitting this PR.
=> Refactor sacct output parsing and add unit test

CHANGELOG.md, cluster_utils/condor_cluster_system.py, cluster_utils/dummy_cluster_system.py, cluster_utils/slurm_cluster_system.py, tests/test_slurm_cluster_system.py
Instead of just checking `$rc == 1` consider all non-zero return codes (except the magic `RETURN_CODE_FOR_RESUME` code) as failure.
This fixes #87 and #42.
- #98
By running examples on Slurm, Condor and locally
=> Consider non-zero return codes as failure

cluster_utils/__init__.py, pyproject.toml
Use setuptools_scm to automatically set the package version based on git tags.  It seems to be quite nice as it gives accurate versions for development branches.  For example with the last version tag currently being v2.5, I now get something like "2.6.dev254+gdc20c3d.d20240521" as version.
Also define `__version__` in the main package `__init__.py` (resolves #82), using the version obtained with importlib (i.e. will use the version that was inferred by setuptools_scm during installation).
- #101
=> Get package version from git and also set `__version__`

cluster_utils/job.py, docs/configuration.rst
Previously, environment variables set in the environment setup were not visible to singularity if running with `--cleanenv` or `--containall`.
Also switch order of setting environment variables and pre_job_script to allow the script to use the environment variables (useful to write more generic scripts).
Partially addresses #68.
=> Pass configured environment variables to singularity

cluster_utils/constants.py, cluster_utils/settings.py, cluster_utils/utils.py, docs/api.rst, docs/conf.py, docs/examples/cluster_main_decorator.rst, docs/examples/index.rst, docs/exit_for_resume.rst, docs/index.rst, examples/basic/main_with_decorator.py
Ass sugested in #95, add dedicated page for API documentation.  The idea is to list all functions here, that are supposed to be used by the user.
- #95
=> docs: Add API Reference page

CHANGELOG.md, README.md, cluster_utils/__init__.py, cluster_utils/client/__init__.py, docs/configuration.rst, docs/troubleshooting.rst, examples/basic/main.py, examples/basic/main_no_fail.py, examples/checkpointing/checkpoint_example.py, examples/slurm_timeout_signal/main.py, tests/main_no_save_metrics.py, tests/test_client_api.py
Rename
- `read_params_from_cmdline` to `initialize_job`, and
- `save_metrics_params` to `finalize_job`.
as discussed in https://github.com/martius-lab/cluster_utils/pull/99#discussion_r1634365846
The purpose of the renaming is to better reflect when/why to call the functions instead of focusing too much on technical details, which are likely of less interest to the user.
The old names are kept as aliases but are marked as deprecated.  Using them will trigger a FutureWarning.
BREAKING: I used this occasion to remove the following options from `initialize_job/read_params_from_cmdline`:
- `make_immutable`: Parameters are always immutable now.  If one really needs a mutable structure, this is still possible by copying the data.
- `save_params`: It simply always saves now.
Let me know if you …
=> Rename read_params_from_cmdline and save_metrics_params

pyproject.toml
NumPy 2 got released, which is unfortunately not compatible with pandas 2.0.3, which we depend on specifically.
As quick fix for now simply restrict to numpy < 2.
This is just for making the currently broken installation work again.  Generally, we should decide how we handle dependency versions but I'll open a separate issue for that.
=> fix: Restrict numpy version to < 2

noxfile.py, pyproject.toml
Based on discussion in #111:
- Relax pandas requirement from `==` to `>=`
- Pin exact versions of all lint tool.  types-* packages for mypy are not pinned, as they are coupled to their actual
library packages (which are not pinned as well).
While already touching this also bump the versions of black and ruff to the latest releases.  For ruff some minor config adjustments and ignoring one rule was necessary.
Closes #111
Via nox.  There are no changes to actual package code, so nothing to test on the cluster.
=> Update dependency versions

README.md, docs/index.rst, docs/usage.rst
- Add a "Usage" page with a bit more information on how to actually run it.  I also added the interactive commands, I hope I got all the descriptions right.
- Revise the start page.  It was based on the old README but didn't get updated accordingly when the README was revised recently.
=> Add dedicated "Usage" page to documentation and revise start page

CHANGELOG.md, docs/api.rst, docs/installation.rst, noxfile.py, pyproject.toml, src/cluster_utils/base/utils.py, src/cluster_utils/client/__init__.py, src/cluster_utils/grid_search.py, src/cluster_utils/hp_optimization.py, src/cluster_utils/scripts/plot_job_timeline.py, src/cluster_utils/server/__init__.py, src/cluster_utils/server/optimizers.py, src/cluster_utils/server/report.py, src/cluster_utils/server/utils.py, tests/grid_search_with_venv.toml, tests/run_integration_tests_with_venv.sh
Move all the dependencies that are only needed for running the main (aka server) process but not for the job scripts into an optional dependencies group "server". This dramatically reduces dependencies for the user code, making installation faster and reducing potential version conflicts.
So now, user code which only needs the client API can simply depend on "cluster_utils" as before, but for running the cluster_utils applications (`grid_search`/`hp_optimization`), one needs to install "cluster_utils[server]".
Imports of these applications are wrapped with `OptionalDependencyImport("server")`, to give the user a useful error message in case the necessary dependencies have not been installed.  For this, `OptionalDependencyImport` has been moved to `base.utils`, so it can be imported …
=> Make server-dependencies optional

src/cluster_utils/server/job_manager.py, src/cluster_utils/server/progress_bars.py, src/cluster_utils/server/utils.py
Handling the shutdown on SIGINT (including sys.exit()) within the signal handler function is problematic as the signal can be received multiple times before the application actually exists.  This results in the duplicated prints and potentially other issues.
Instead, only set a flag in the signal handler, which is then checked in each iteration of the main loop.  Add a simple `SignalWatcher` utility class for this.
Unfortunately this adds more redundant code in `hp_optimization()` and `grid_search()` but I don't see an easy way to avoid that at the moment.
And another change that is indirectly related as it was necessary to avoid messy output:
Use context manager for the progress bars to make sure they are properly closed when the loop finishes.  This results in much nicer output, as …
=> Handle shutdown outside of signal handler & use context manager for progress bars

src/cluster_utils/base/utils.py
The error message in OptionalDependencyNotFoundError was still using the package name "cluster" in the install command.  Change this to use the new name "cluster_utils".
=> fix: Use correct package name in error message

.github/workflows/nox.yml, noxfile.py
We should keep track with new Python versions.
Python 3.8 actually reached EOL, so we could drop support for it.  However, I'd keep it for now and only drop it if there is an actual reason (e.g. a dependency issue or newer language feature that we want to use).
=> chore: Run linter/tests also for Python 3.12 and 3.13

src/cluster_utils/server/report.py
So far, a failure during report generation was logged but not printed to the terminal, so it could easily be missed by the user.
To change this, also print an explicit, red warning to the terminal in that case.
=> Print warning when report generation failed.

CHANGELOG.md, src/cluster_utils/server/utils.py
got a file not found error before any jobs started
fixed it by replacing "os.mkdir(cache_dir)" with "os.makedirs(cache_dir)" in line 290 in cluster_utils/server/utils.py
=> create intermediate folders for cache_dir
